import { defineConfig } from 'vite';
import { cpSync, copyFileSync, createReadStream, existsSync, statSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { WORDMARK } from './src/ui/wordmark.js';

const ROOT = path.dirname(fileURLToPath(import.meta.url));

const TYPES = {
  '.json': 'application/json',
  '.md': 'text/markdown; charset=utf-8',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.png': 'image/png',
  '.webp': 'image/webp',
};

/**
 * saints/ and data/ are content, not source, and live outside Vite's publicDir
 * so that the one-folder contract stays visible at the repo root. This plugin
 * closes the gap: in dev it serves both directories; at build it copies them
 * into dist/ and ships a copy of index.html as 404.html, which is how GitHub
 * Pages serves a single-page app's deep links (/calendar/2026-08-20 has no
 * file behind it; Pages falls through to 404.html, which is the app).
 */
const contentDirs = () => ({
  name: 'gallery-content-dirs',

  configureServer(server) {
    server.middlewares.use((req, res, next) => {
      const url = decodeURIComponent((req.url ?? '').split('?')[0]);
      const top = url.startsWith('/saints/') ? 'saints' : url.startsWith('/data/') ? 'data' : null;
      if (!top) return next();

      // Resolve, then confine to the directory the URL claimed — confining
      // only to the repo root would let /saints/../package.json through.
      const dir = path.join(ROOT, top) + path.sep;
      const file = path.resolve(ROOT, url.slice(1));
      if (!file.startsWith(dir) || !existsSync(file) || !statSync(file).isFile()) {
        res.statusCode = 404;
        return res.end('not found');
      }
      res.setHeader('Content-Type', TYPES[path.extname(file).toLowerCase()] ?? 'application/octet-stream');
      createReadStream(file).pipe(res);
    });
  },

  closeBundle() {
    cpSync(path.join(ROOT, 'saints'), path.join(ROOT, 'dist/saints'), { recursive: true });
    cpSync(path.join(ROOT, 'data'), path.join(ROOT, 'dist/data'), { recursive: true });
    copyFileSync(path.join(ROOT, 'dist/index.html'), path.join(ROOT, 'dist/404.html'));
  },
});

/**
 * The two Latin subsets, preloaded (Addendum G6; author, 2026-08-28: "ignore
 * svg, just preload texts as recommended").
 *
 * `font-display: optional` stands, and is the reason this is worth doing at
 * all: optional gives the file about a hundred milliseconds and then keeps the
 * fallback *for the life of the page*, so on a cold load the reader either gets
 * Literata or does not, and no amount of later arrival changes it. A preload
 * starts the request with the HTML instead of after the stylesheet has been
 * parsed and matched, which is what puts the face inside that window on most
 * loads — without reintroducing the layout shift `swap` would cost. Zero shift
 * outranks brand (DESIGN.md); this buys the brand back where it is free.
 *
 * **Which two, and why not four.** `normal-latin` is the face every page is set
 * in. `normal-latin-ext` is not a luxury beside it: the corpus is full of names
 * like *Cyriacus of Tazlău*, whose accented characters live in that subset, so
 * a page given one and not the other would change face mid-word — the same
 * failure the display face's own scoping comment in base.css describes. Italic
 * is deliberately left out: it appears inside lives and quotations rather than
 * at first paint, and two more files would spend the budget this exists to
 * protect.
 *
 * **Why a plugin rather than a line in index.html.** Vite hashes the filenames,
 * so the name cannot be written down; `transformIndexHtml` runs with the
 * finished bundle and can look an emitted asset up by its source name.
 * `crossorigin` is not optional on a font preload — without it the browser
 * fetches the file a second time for the CSS, and the preload becomes a cost
 * rather than a saving.
 */
/**
 * The masthead, as outlines, in the HTML itself.
 *
 * The stamp face is the only one here at `font-display: swap` and the only one
 * not preloaded, so a cold load printed the name in Literata and swapped it a
 * moment later (author, 2026-08-28). A path has no loading window — but it only
 * helps if it is in the *first* paint, which means the markup rather than a
 * module that has to parse first. The veil is the whole point: it is what a
 * reader looks at while the modules are still arriving.
 *
 * One source: `src/ui/wordmark.js` is generated by `scripts/make_wordmark.py`
 * from the font's own outlines, and this substitutes it into both slots so the
 * SVG is never hand-copied into markup where it would drift.
 */
const wordmark = () => ({
  name: 'gallery-wordmark',
  transformIndexHtml: {
    order: 'pre',
    handler(html) {
      if (!html.includes('<!--wordmark-->')) {
        this.warn('wordmark: no <!--wordmark--> slot in index.html');
        return html;
      }
      return html.replaceAll('<!--wordmark-->', WORDMARK);
    },
  },
});

const preloadLatin = () => ({
  name: 'gallery-preload-latin',
  apply: 'build',
  enforce: 'post',

  transformIndexHtml: {
    order: 'post',
    handler(html, ctx) {
      const base = process.env.BASE_PATH || '/';
      /*
       * Matched on the asset's **own record of where it came from**, not on
       * its emitted name. The first build here did the latter and shipped the
       * same subset twice: Vite's hash can itself begin with a hyphen —
       * `literata-normal-latin-ext--vWOuwpV.woff2` — so any pattern loose
       * enough to match a hash after `literata-normal-latin-` also matches
       * `ext-` and the plain Latin file was never found. The bundle knows the
       * source it emitted each asset from; asking it removes the guess.
       */
      const sourceOf = (asset) =>
        [...(asset.originalFileNames ?? []), asset.name ?? '']
          .map((name) => String(name).split('/').pop())
          .filter(Boolean);
      const emitted = Object.values(ctx.bundle ?? {}).filter(
        (asset) => typeof asset.fileName === 'string' && asset.fileName.endsWith('.woff2'),
      );
      const tags = [];
      for (const stem of ['literata-normal-latin', 'literata-normal-latin-ext']) {
        const found = emitted.find((asset) => sourceOf(asset).includes(`${stem}.woff2`))?.fileName;
        if (!found) {
          // Loud rather than silent: a renamed or dropped subset should break
          // the build's claim about itself, not quietly ship no preload.
          this.warn(`preload: no built file for ${stem}.woff2`);
          continue;
        }
        tags.push({
          tag: 'link',
          attrs: { rel: 'preload', as: 'font', type: 'font/woff2', crossorigin: '', href: base + found },
          injectTo: 'head-prepend',
        });
      }
      return { html, tags };
    },
  },
});

export default defineConfig({
  // '/' locally; CI sets BASE_PATH to '/<repo>/' for project Pages. A custom
  // domain later means removing the variable from the workflow, nothing else.
  base: process.env.BASE_PATH || '/',
  plugins: [contentDirs(), wordmark(), preloadLatin()],
});
