#!/usr/bin/env node
/**
 * Extracts vertical metrics from the committed WOFF2 files and emits them as
 * CSS custom properties (Addendum C3, capsize-style). Line boxes derived from
 * the actual font mean a typeface change recalculates layout instead of
 * forcing a re-measure of every consumer, and the `.names` class can bound
 * its line-height in a way that script-fallback substitution cannot push.
 *
 * Run after scripts/fetch-fonts.mjs; the output (src/styles/metrics.css) is
 * committed. No dependency: WOFF2's table data is one Brotli stream, which
 * node:zlib decompresses, and the three tables read here — head, hhea, OS/2 —
 * are stored verbatim (only glyf/loca/hmtx have WOFF2 transforms).
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { brotliDecompressSync } from 'node:zlib';

// WOFF2's known-table-tags list; a directory entry's flags index into it.
// prettier-ignore
const KNOWN_TAGS = [
  'cmap','head','hhea','hmtx','maxp','name','OS/2','post','cvt ','fpgm',
  'glyf','loca','prep','CFF ','VORG','EBDT','EBLC','gasp','hdmx','kern',
  'LTSH','PCLT','VDMX','vhea','vmtx','BASE','GDEF','GPOS','GSUB','EBSC',
  'JSTF','MATH','CBDT','CBLC','COLR','CPAL','SVG ','sbix','acnt','avar',
  'bdat','bloc','bsln','cvar','fdsc','feat','fmtx','fvar','gvar','hsty',
  'just','lcar','mort','morx','opbd','prop','trak','Zapf','Silf','Glat',
  'Gloc','Feat','Sill',
];

function readUIntBase128(buf, pos) {
  let value = 0;
  for (let i = 0; i < 5; i++) {
    const byte = buf[pos + i];
    value = (value << 7) | (byte & 0x7f);
    if ((byte & 0x80) === 0) return [value >>> 0, pos + i + 1];
  }
  throw new Error('UIntBase128 ran past five bytes');
}

export function woff2Metrics(file) {
  const buf = readFileSync(file);
  if (buf.toString('latin1', 0, 4) !== 'wOF2') throw new Error(`${file} is not WOFF2`);
  const numTables = buf.readUInt16BE(12);

  let pos = 48;
  const tables = [];
  for (let i = 0; i < numTables; i++) {
    const flags = buf[pos++];
    let tag;
    if ((flags & 0x3f) === 0x3f) {
      tag = buf.toString('latin1', pos, pos + 4);
      pos += 4;
    } else {
      tag = KNOWN_TAGS[flags & 0x3f];
    }
    const transform = (flags >>> 6) & 0x03;
    let origLength, transformLength;
    [origLength, pos] = readUIntBase128(buf, pos);
    // glyf and loca are transformed when version is 0; every other table is
    // transformed only when the version is non-zero. Transformed entries carry
    // an explicit length; verbatim ones occupy origLength in the stream.
    const transformed = tag === 'glyf' || tag === 'loca' ? transform === 0 : transform !== 0;
    if (transformed) [transformLength, pos] = readUIntBase128(buf, pos);
    tables.push({ tag, size: transformed ? transformLength : origLength });
  }

  const data = brotliDecompressSync(buf.subarray(pos));
  let offset = 0;
  const at = {};
  for (const t of tables) {
    at[t.tag] = offset;
    offset += t.size;
  }

  const upm = data.readUInt16BE(at.head + 18);
  const os2 = at['OS/2'];
  const version = data.readUInt16BE(os2);
  return {
    upm,
    typoAscender: data.readInt16BE(os2 + 68),
    typoDescender: data.readInt16BE(os2 + 70),
    typoLineGap: data.readInt16BE(os2 + 72),
    capHeight: version >= 2 ? data.readInt16BE(os2 + 88) : null,
    xHeight: version >= 2 ? data.readInt16BE(os2 + 86) : null,
    hheaAscender: data.readInt16BE(at.hhea + 4),
    hheaDescender: data.readInt16BE(at.hhea + 6),
  };
}

const r4 = (n) => Math.round(n * 10000) / 10000;

function main() {
  // Every subset of one style shares metrics; the roman latin file is the
  // canonical source, and the italic is read only to confirm agreement.
  const roman = woff2Metrics('src/fonts/literata-normal-latin.woff2');
  const italic = woff2Metrics('src/fonts/literata-italic-latin.woff2');

  const ratio = (m) => ({
    cap: r4(m.capHeight / m.upm),
    x: r4(m.xHeight / m.upm),
    ascent: r4(m.typoAscender / m.upm),
    descent: r4(Math.abs(m.typoDescender) / m.upm),
    gap: r4(m.typoLineGap / m.upm),
  });
  const r = ratio(roman);
  const lineBox = r4(r.ascent + r.descent + r.gap);

  const css = `/* GENERATED by scripts/font-metrics.mjs from the committed Literata files —
   do not hand-edit; re-run after changing fonts. Em-ratios from the font's
   own tables (unitsPerEm ${roman.upm}). The line-box value is the font's
   natural single-line height; consumers bound line-height with these so
   script-fallback substitution can never change a measured layout.
   Italic agreement check: cap ${ratio(italic).cap}, ascent ${ratio(italic).ascent}. */

:root {
  --font-cap: ${r.cap}; /* cap height / em */
  --font-x: ${r.x}; /* x-height / em */
  --font-ascent: ${r.ascent}; /* typo ascender / em */
  --font-descent: ${r.descent}; /* |typo descender| / em */
  --font-line-gap: ${r.gap};
  --font-line-box: ${lineBox}; /* natural line box, em */
}
`;
  writeFileSync('src/styles/metrics.css', css);
  console.log(`metrics.css written: cap ${r.cap}, ascent ${r.ascent}, descent ${r.descent}, line box ${lineBox}`);
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].replace(/\\/g, '/').split('/').pop())) {
  main();
}
