#!/usr/bin/env node
/**
 * Regenerates the index at the top of SESSIONS.md.
 *
 * `node scripts/sessions-index.mjs`
 *
 * SESSIONS.md is the project's memory: every decision, in the order it was
 * taken, with the reasoning that produced it. It is 5,000 lines and grows by a
 * couple of hundred each sitting, and the author's instruction (2026-08-28) was
 * to index it and **leave it whole** — end-to-end readability is worth more
 * than shorter files.
 *
 * The amendments are written in two shapes, which is part of why the file is
 * hard to move around in: 1 to 41 are bold-numbered paragraphs inside one long
 * section, 42 onward are `## Amendment N` headings of their own. This reads
 * both, so the index does not depend on anyone settling that.
 *
 * Idempotent: it rewrites whatever sits between the two markers and touches
 * nothing else, so it can be run after every sitting.
 */

import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const FILE = path.join(ROOT, 'SESSIONS.md');

const START = '<!-- index:start -->';
const END = '<!-- index:end -->';

/** GitHub's own anchor rule, near enough for the headings this file has. */
const anchor = (heading) =>
  heading
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-');

const text = await readFile(FILE, 'utf8');
const lines = text.split('\n');

const entries = [];

/*
 * The bold-numbered shape is only the *original* amendment section, which runs
 * until the first `## Amendment` heading. Past that, `**1.` is an ordinary
 * numbered list inside somebody's prose — three of them, which is how this was
 * found.
 */
const firstHeading = lines.findIndex((l) => /^## Amendment \d+/.test(l));
const boldEnds = firstHeading === -1 ? lines.length : firstHeading;

for (let i = 0; i < lines.length; i += 1) {
  const line = lines[i];

  // 42 onward: "## Amendment 52 — title (2026-08-27, eleventh sitting)"
  const heading = line.match(/^## Amendment (\d+)\s*[—-]\s*(.*)$/);
  if (heading) {
    const [, n, rest] = heading;
    const when = rest.match(/\(([^)]*\d{4}-\d{2}-\d{2}[^)]*)\)\s*$/);
    entries.push({
      n: Number(n),
      title: rest.replace(/\s*\([^)]*\)\s*$/, '').trim(),
      when: when ? when[1] : '',
      link: '#' + anchor(line.replace(/^##\s*/, '')),
    });
    continue;
  }

  // 1 to 41: "**7. The glyph beside a name is now the rite x communion matrix,"
  const bold = i < boldEnds ? line.match(/^\*\*(\d+)\.\s+(.*)$/) : null;
  if (bold) {
    const [, n] = bold;
    // the title can wrap over several lines before the closing **
    let title = bold[2];
    let j = i;
    while (!title.includes('**') && j + 1 < lines.length && j - i < 4) {
      j += 1;
      title += ' ' + lines[j].trim();
    }
    title = title.slice(0, title.indexOf('**') === -1 ? undefined : title.indexOf('**'));
    const when = title.match(/(\d{4}-\d{2}-\d{2})/);
    entries.push({
      n: Number(n),
      title: title.replace(/\s*\(?(author,\s*)?\d{4}-\d{2}-\d{2}\)?[.:]?\s*$/, '').replace(/\s+/g, ' ').trim(),
      when: when ? when[1] : '',
      link: '',
    });
  }
}

entries.sort((a, b) => a.n - b.n);

// A number written twice is a mistake worth failing on rather than indexing.
const seen = new Set();
const duplicates = entries.filter((e) => (seen.has(e.n) ? true : (seen.add(e.n), false)));
if (duplicates.length) {
  console.error(`Amendment numbers used twice: ${duplicates.map((d) => d.n).join(', ')}`);
  process.exitCode = 1;
}

const rows = entries.map((e) => {
  const title = e.link ? `[${e.title}](${e.link})` : e.title;
  return `| ${e.n} | ${title} | ${e.when} |`;
});

const index = [
  START,
  '',
  '## The amendments, in order',
  '',
  '*Generated by `node scripts/sessions-index.mjs`. Do not edit between the',
  'markers; edit the amendment and run it again.*',
  '',
  `${entries.length} amendments. 1 to 41 are bold-numbered paragraphs in the`,
  'section below and are not linkable; 42 onward have headings of their own.',
  '',
  '| # | What it settled | When |',
  '|---|---|---|',
  ...rows,
  '',
  END,
].join('\n');

const has = text.includes(START) && text.includes(END);
const next = has
  ? text.slice(0, text.indexOf(START)) + index + text.slice(text.indexOf(END) + END.length)
  : lines[0] + '\n\n' + index + '\n' + lines.slice(1).join('\n');

await writeFile(FILE, next);
console.log(`indexed ${entries.length} amendments${has ? ' (regenerated)' : ' (index added)'}`);
