import { chromium } from '@playwright/test';
const url = process.argv[2] ?? 'http://localhost:5173/';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 360, height: 900 } });
const seen = [];
page.on('console', (m) => { if (m.type() === 'error') seen.push('console: ' + m.text()); });
page.on('pageerror', (e) => seen.push('pageerror: ' + e.name + ': ' + e.message + '\n' + (e.stack ?? '')));
page.on('requestfailed', (r) => seen.push('reqfail: ' + r.url() + ' ' + r.failure()?.errorText));
await page.goto(url, { waitUntil: 'domcontentloaded' }).catch((e) => seen.push('goto: ' + e.message));
await page.waitForTimeout(3000);
console.log(JSON.stringify(seen.slice(0, 5), null, 1));
await browser.close();
